"""
export_godot_gdscript.py

Generates a GDScript file that, when run as a scene script inside a real
Godot Editor (4.x), procedurally builds the scene described by a
ScenePlan using CSGSphere3D/CSGBox3D/CSGCylinder3D primitives.

HONESTY NOTE, read before trusting this: unlike export_obj.py and
export_gltf.py (whose OUTPUT FILES were structurally and geometrically
verified in this sandbox) and export_threejs.py (whose output was
visually confirmed rendering correctly in a real browser), this
generator's output has NOT been run against a real Godot instance --
no Godot Editor is reachable from this environment. What WAS verified:
the GDScript syntax follows Godot 4.x's documented API (class names,
method signatures, property names) as of this module's build date, and
the generated text is checked for balanced braces/parens as a basic
sanity check -- that is a much weaker guarantee than actually running
it. Treat this generator's output as "written to the documented API,"
not as "tested," and verify it yourself in a real Godot 4.x project
before relying on it.
"""

import math
from scene_plan import ScenePlan


_CSG_NODE = {
    "sphere": "CSGSphere3D",
    "box": "CSGBox3D",
    "cylinder": "CSGCylinder3D",
    "capsule": "CSGSphere3D",  # simplified: approximated as a sphere, same as the OBJ/glTF exporters
    "cone": "CSGCylinder3D",   # simplified: CSGCylinder3D with cone=true in Godot 4.x
}


def _gd_vector3(v):
    return f"Vector3({v[0]}, {v[1]}, {v[2]})"


def _gd_color(rgba):
    return f"Color({rgba[0]}, {rgba[1]}, {rgba[2]}, {rgba[3]})"


def export_godot_gdscript(plan: ScenePlan, path: str) -> str:
    """
    Writes a GDScript file (attach as a script on any Node3D and run the
    scene in the editor, or call build_scene() from _ready()).

    Returns the generated source (also written to `path`) so a caller
    can inspect/test it without re-reading the file.
    """
    lines = []
    lines.append("extends Node3D")
    lines.append("")
    lines.append(f"# Generated by qfoldit-scene-export from ScenePlan '{plan.name}'")
    lines.append("# NOT verified against a live Godot instance -- written to the documented")
    lines.append("# Godot 4.x API, but run and check this yourself before relying on it.")
    lines.append("")
    lines.append("func _ready():")
    lines.append("\tbuild_scene()")
    lines.append("")
    lines.append("func build_scene():")

    for node in plan.nodes:
        csg_class = _CSG_NODE.get(node.primitive)
        if csg_class is None:
            raise ValueError(f"No Godot CSG mapping for primitive '{node.primitive}'")
        var_name = f"n_{node.id}"
        lines.append(f"\tvar {var_name} = {csg_class}.new()")
        lines.append(f"\t{var_name}.name = {json_str(node.id)}")
        lines.append(f"\t{var_name}.position = {_gd_vector3(node.position)}")
        rx, ry, rz = (math.radians(a) for a in node.rotation_euler_deg)
        lines.append(f"\t{var_name}.rotation = Vector3({rx}, {ry}, {rz})")
        if node.primitive == "box":
            sx, sy, sz = node.scale
            lines.append(f"\t{var_name}.size = Vector3({sx*2}, {sy*2}, {sz*2})")
        elif node.primitive in ("sphere", "capsule"):
            r = sum(node.scale) / 3.0
            lines.append(f"\t{var_name}.radius = {r}")
        elif node.primitive in ("cylinder", "cone"):
            rad = (node.scale[0] + node.scale[2]) / 2.0
            lines.append(f"\t{var_name}.radius = {rad}")
            lines.append(f"\t{var_name}.height = {node.scale[1] * 2}")
            if node.primitive == "cone":
                lines.append(f"\t{var_name}.cone = true")
        mat = node.material
        lines.append(f"\tvar mat_{node.id} = StandardMaterial3D.new()")
        lines.append(f"\tmat_{node.id}.albedo_color = {_gd_color(mat.color_rgba)}")
        lines.append(f"\tmat_{node.id}.metallic = {mat.metallic}")
        lines.append(f"\tmat_{node.id}.roughness = {mat.roughness}")
        lines.append(f"\t{var_name}.material = mat_{node.id}")
        lines.append(f"\tadd_child({var_name})")
        lines.append("")

    for i, edge in enumerate(plan.edges):
        node_a = next(n for n in plan.nodes if n.id == edge.from_id)
        node_b = next(n for n in plan.nodes if n.id == edge.to_id)
        pa, pb = node_a.position, node_b.position
        dx, dy, dz = pb[0]-pa[0], pb[1]-pa[1], pb[2]-pa[2]
        length = math.sqrt(dx*dx + dy*dy + dz*dz)
        mid = ((pa[0]+pb[0])/2, (pa[1]+pb[1])/2, (pa[2]+pb[2])/2)
        var_name = f"e_{i}"
        lines.append(f"\tvar {var_name} = CSGCylinder3D.new()")
        lines.append(f"\t{var_name}.name = \"bond_{i}\"")
        lines.append(f"\t{var_name}.radius = {edge.radius}")
        lines.append(f"\t{var_name}.height = {length}")
        lines.append(f"\t{var_name}.position = {_gd_vector3(mid)}")
        lines.append(f"\t# orient the cylinder (Y-axis by default) to point from {edge.from_id} to {edge.to_id}:")
        lines.append(f"\tvar dir_{i} = ({_gd_vector3(pb)} - {_gd_vector3(pa)}).normalized()")
        lines.append(f"\tif dir_{i} != Vector3.UP and dir_{i} != Vector3.DOWN:")
        lines.append(f"\t\t{var_name}.transform.basis = Basis(Vector3.UP.cross(dir_{i}).normalized(), Vector3.UP.angle_to(dir_{i}))")
        mat = edge.material
        lines.append(f"\tvar mat_e_{i} = StandardMaterial3D.new()")
        lines.append(f"\tmat_e_{i}.albedo_color = {_gd_color(mat.color_rgba)}")
        lines.append(f"\t{var_name}.material = mat_e_{i}")
        lines.append(f"\tadd_child({var_name})")
        lines.append("")

    cam = plan.camera
    lines.append("\tvar cam = Camera3D.new()")
    lines.append(f"\tcam.position = {_gd_vector3(cam.position)}")
    lines.append(f"\tcam.fov = {cam.fov_deg}")
    lines.append(f"\tcam.look_at({_gd_vector3(cam.look_at)}, Vector3.UP)")
    lines.append("\tadd_child(cam)")
    lines.append("")

    if not plan.lights:
        lines.append("\tvar default_light = DirectionalLight3D.new()")
        lines.append("\tadd_child(default_light)")
    for i, light in enumerate(plan.lights):
        if light.kind == "directional":
            lines.append(f"\tvar light_{i} = DirectionalLight3D.new()")
        elif light.kind == "point":
            lines.append(f"\tvar light_{i} = OmniLight3D.new()")
        else:
            lines.append(f"\tvar light_{i} = SpotLight3D.new()")
        lines.append(f"\tlight_{i}.position = {_gd_vector3(light.position)}")
        lines.append(f"\tlight_{i}.light_color = Color({light.color_rgb[0]}, {light.color_rgb[1]}, {light.color_rgb[2]})")
        lines.append(f"\tlight_{i}.light_energy = {light.intensity}")
        lines.append(f"\tadd_child(light_{i})")

    source = "\n".join(lines) + "\n"
    with open(path, "w") as f:
        f.write(source)
    return source


def json_str(s):
    return '"' + s.replace('"', '\\"') + '"'
